-- SEO pass for the 13 newly-approved couple prompts (2026-07-12) — all approved (dates
-- 2026-07-08..12), all had EMPTY description/how_to_use and empty tags ('[]').
-- Touches ONLY SEO fields: title, description (meta), how_to_use (rendered body), tags.
-- prompt_text is NEVER modified. Keyword targeting per seo/keyword-research.md +
-- seo/tracklist.md: couple prompt / gemini couple photo prompt / gemini ai photo prompt
-- (copy paste), Nano Banana, India/SE-Asia. Descriptions are structurally unique (no shared
-- boilerplate). Backup of prior (empty) values: seo/new-prompts-backup-2026-07-12.json.
-- 11 slugs renamed in rename-descriptive-slugs-2026-07-12.sql (run that FIRST).

-- ===== Couple: dusk lakeside, luxury convertible, black-tie editorial =====
UPDATE prompts SET title='Luxury Car Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a moody dusk scene by a lake, black suit and backless gown draped over a luxury convertible, red taillights and cinematic film grain. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. A vertical frame keeps the car''s rear, the gown''s train and the hillside lights in shot — re-run once if the low dusk light darkens a face.', tags='["ai photo prompt","gemini prompt","couple prompt","cinematic prompt","fashion prompt"]' WHERE slug='couple-prompt-luxury-car';

-- ===== Couple: vintage speakeasy billiards room, pool-table flirtation =====
UPDATE prompts SET title='Romantic Couple Prompt – Gemini AI Photo Prompt', description='Romantic couple prompt for Gemini AI — a playful pool-table moment in a vintage speakeasy bar, white mini dress, rolled sleeves and warm tungsten film tones. Copy, paste in Nano Banana & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this romantic couple prompt into Nano Banana (Gemini) or ChatGPT. Keep the full-body vertical frame so the pool cues and gallery wall stay in shot — re-run once if the warm tungsten grade shifts skin tones.', tags='["ai photo prompt","gemini prompt","couple prompt","vintage prompt","editorial prompt"]' WHERE slug='romantic-couple-prompt';

-- ===== Couple: 1970s Moroccan riad terrace, mosaic wall, retro editorial =====
UPDATE prompts SET title='Vintage Editorial Couple Prompt – Gemini AI Photo', description='Vintage editorial couple prompt for Gemini AI — a retro 1970s lounge on a Moroccan riad terrace, mosaic tiles, tinted sunglasses and sepia film grain. Copy, paste in Nano Banana & ChatGPT.', how_to_use='Upload one clear couple photo, then copy-paste this vintage editorial couple prompt into Nano Banana (Gemini) or ChatGPT. Both faces are partly styled with sunglasses — say "keep our faces recognizable" if the likeness drifts, and re-run once if the sepia grade flattens the mosaic wall.', tags='["ai photo prompt","gemini prompt","couple prompt","vintage prompt","editorial prompt"]' WHERE slug='vintage-editorial-couple-prompt';

-- ===== Couple: ivory saree at a vintage mirror, admiring glance from the doorway =====
UPDATE prompts SET title='Vintage Mirror Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — she fixes an earring at an ornate vintage mirror in an ivory saree while he watches from the doorway, warm candlelit amber tones. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. Her face appears only in the mirror reflection — re-run once if the reflection blurs, and keep the vertical frame so the doorway and mirror both stay in shot.', tags='["ai photo prompt","gemini prompt","couple prompt","indian aesthetic prompt","cinematic prompt"]' WHERE slug='couple-prompt-vintage-mirror';

-- ===== Couple: old European town, vintage Vespa, polka-dot romper =====
UPDATE prompts SET title='Vespa Street Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a candid old-town European street moment on a cream vintage Vespa, yellow polka-dot romper and golden afternoon light. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. A head-to-toe vertical frame keeps the Vespa and stone alley in shot — re-run once if the candid lip-gloss gesture hides too much of her face.', tags='["ai photo prompt","gemini prompt","couple prompt","travel prompt","aesthetic prompt"]' WHERE slug='couple-prompt-vespa-street';

-- ===== Couple: sailing yacht bow deck, golden hour, white linen =====
UPDATE prompts SET title='Yacht Deck Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a golden-hour editorial on a white sailing yacht, open linen shirt at the mast and a flowing halter dress on the bow. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. Both wear sunglasses in this look — add "no sunglasses" if you want faces fully visible, and keep the vertical frame so the mast, rigging and coastline stay in shot.', tags='["ai photo prompt","gemini prompt","couple prompt","editorial prompt","travel prompt"]' WHERE slug='couple-prompt-yacht-deck';

-- ===== Couple: golden-hour kiss in the rain, hidden roses, pink scooter =====
UPDATE prompts SET title='Rain Kiss Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a passionate kiss in golden-hour rain, one leg kicked up, red roses hidden behind his back and a vintage pink scooter. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. A full-body vertical frame keeps the kicked-up leg, scooter and rain streaks in shot — re-run once if the backlit raindrops soften the faces.', tags='["ai photo prompt","gemini prompt","couple prompt","cinematic prompt","aesthetic prompt"]' WHERE slug='couple-prompt-rain-kiss';

-- ===== Couple: haveli archway, jasmine strand tied at her ankle =====
UPDATE prompts SET title='Jasmine Anklet Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — he ties a jasmine strand around her ankle in a sunlit haveli archway, lavender saree and dreamy golden haze. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. His head is bowed toward her ankle in this pose — re-run once if his face turns away completely, and keep the vertical frame for the arched stone doorway.', tags='["ai photo prompt","gemini prompt","couple prompt","indian aesthetic prompt","aesthetic prompt"]' WHERE slug='couple-prompt-jasmine-anklet';

-- ===== Couple: getting-ready bedroom, draping the mustard silk saree =====
UPDATE prompts SET title='Saree Draping Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a getting-ready moment as he helps drape her mustard-yellow silk saree, cream kurta, gold jhumkas and soft window light. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. A mid-thigh-up frame keeps the saree pleats and dresser mirror in shot — re-run once if her three-quarter profile loses the likeness.', tags='["ai photo prompt","gemini prompt","couple prompt","indian aesthetic prompt","cinematic prompt"]' WHERE slug='couple-prompt-saree-draping';

-- ===== Couple: carnival dip pose, illuminated ferris wheel at dusk =====
UPDATE prompts SET title='Ferris Wheel Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a laughing dip pose at a dusk carnival, illuminated ferris wheel behind, film grain and golden-to-blue-hour light. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. The low camera angle puts the ferris wheel in the upper-left — keep the vertical frame, and re-run once if the dip pose bends a face out of view.', tags='["ai photo prompt","gemini prompt","couple prompt","aesthetic prompt","cinematic prompt"]' WHERE slug='couple-prompt-ferris-wheel';

-- ===== Couple: night ghat steps, kulhad chai, fairy-light glow =====
UPDATE prompts SET title='Kulhad Chai Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a cozy night on heritage ghat steps sharing kulhad chai, warm fairy lights and analog film glow. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. The warm string-light glow is the key mood — re-run once if the night scene comes out too dark, and keep the vertical frame so the heritage tower stays in shot.', tags='["ai photo prompt","gemini prompt","couple prompt","indian aesthetic prompt","travel prompt"]' WHERE slug='couple-prompt-kulhad-chai';

-- ===== Couple: weathered orange haveli door, fastening her blouse clasp =====
UPDATE prompts SET title='Haveli Door Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — he fastens her clasp before a weathered orange haveli door, beige saree, marigold garlands and terracotta film tones. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. She looks back over her shoulder in this pose, so her face carries the frame — re-run once if the over-shoulder turn distorts it, keeping the waist-up vertical crop.', tags='["ai photo prompt","gemini prompt","couple prompt","indian aesthetic prompt","vintage prompt"]' WHERE slug='couple-prompt-haveli-door';

-- ===== Couple: backlit close-up, sunflower and pink carnation, interlaced hands =====
UPDATE prompts SET title='Sunflower Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a backlit close-up with heads resting together, hands interlaced around a sunflower and a pink carnation, nostalgic film glow. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. This is a tight close-up, so likeness matters most — re-run once if either face softens in the backlit haze, and keep the 3:4 portrait crop for the crossed flower stems.', tags='["ai photo prompt","gemini prompt","couple prompt","aesthetic prompt","nature prompt"]' WHERE slug='couple-prompt-sunflower';

-- ===== Couple: sharing a clear umbrella in gentle rain (added later same day) =====
UPDATE prompts SET title='Clear Umbrella Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — laughing close under one clear umbrella in gentle garden rain, pastel outfits and soft cinematic bokeh. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. The transparent canopy should leave both faces visible through it — re-run once if the umbrella reflections blur them, keeping the medium-close vertical frame.', tags='["ai photo prompt","gemini prompt","couple prompt","aesthetic prompt","cinematic prompt"]' WHERE slug='couple-prompt-clear-umbrella';

-- ===== Couple: vintage carousel at dusk, film-camera candid (added later same day) =====
UPDATE prompts SET title='Carousel Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — he playfully snaps her on a film camera before a glowing vintage carousel at dusk, shy laugh, golden-hour film grade. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. The camera covers part of his face and her hand is raised to her cheek — re-run once if either likeness slips, keeping the vertical frame so the lit carousel fills the background.', tags='["ai photo prompt","gemini prompt","couple prompt","aesthetic prompt","vintage prompt"]' WHERE slug='couple-prompt-carousel';
