-- SEO pass for the 9 scheduled prompts (2026-07-15..17) — all had EMPTY description,
-- how_to_use and tags ('[]'). Touches ONLY SEO fields: title, description (meta),
-- how_to_use (rendered body), tags. prompt_text is NEVER modified. Keyword targeting per
-- seo/keyword-research.md + seo/tracklist.md. Descriptions are structurally unique.
-- Backup of prior values: seo/new-prompts-backup-2026-07-15.json.
-- All 9 slugs renamed in rename-descriptive-slugs-2026-07-15.sql (run that FIRST).
-- Also: tags backfill for the 8 style/ChatGPT prompts from 2026-06-24 that predate the
-- tags workflow (title/desc/how_to_use already done, only tags were '[]').
-- ===== night selfie, lipstick kiss marks on his cheek, cozy bedroom light =====
UPDATE prompts SET title='Kiss Marks Couple Selfie – Gemini AI Photo Prompt', description='Playful Gemini AI couple photo prompt — a night selfie where lipstick kiss marks cover his cheek while she cups his chin, soft warm bedroom light. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear selfie of you both, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. The kiss marks should sit on the cheek and jawline only — if they spread across the face, re-run and ask for fewer, cleaner imprints.', tags='["ai photo prompt", "gemini prompt", "couple prompt", "selfie prompt", "aesthetic prompt"]' WHERE slug='couple-prompt-kiss-marks';
-- ===== sunflower bouquet in kraft paper, cobblestone European street, green knit sweater =====
UPDATE prompts SET title='Sunflower Bouquet Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt for women — seated on a cobblestone European street with a kraft-paper sunflower bouquet, green knit sweater and a soft smile. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear front-facing photo, then copy-paste this portrait prompt into Nano Banana (Gemini) or ChatGPT. Keep the sunflowers against the lap so they do not cover the face, and re-run once if the row houses behind lose their brick texture.', tags='["ai photo prompt", "gemini prompt", "portrait prompt", "women portrait prompt", "aesthetic prompt"]' WHERE slug='sunflower-bouquet-portrait-prompt';
-- ===== red shirt, ornate black baroque armchair, gold chain =====
UPDATE prompts SET title='Red Shirt Baroque Portrait – Gemini AI Photo Prompt', description='Moody Gemini AI photo prompt for men — seated in a carved black baroque armchair in a red button-up, gold chain and rolled sleeves, editorial light. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear front-facing photo, then copy-paste this men portrait prompt into Nano Banana (Gemini) or ChatGPT. The carved armchair does the styling work — if the scrollwork comes out mushy, ask for sharper wood detail rather than more contrast.', tags='["ai photo prompt", "gemini prompt", "portrait prompt", "men portrait prompt", "editorial prompt"]' WHERE slug='red-shirt-baroque-portrait-prompt';
-- ===== outdoor metal staircase, rose garden, sunglasses adjust =====
UPDATE prompts SET title='Garden Staircase Portrait – Gemini AI Photo Prompt', description='Fresh Gemini AI photo prompt for men — standing on a garden staircase among red roses, one hand adjusting sunglasses, relaxed daylight styling. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear photo, then copy-paste this men portrait prompt into Nano Banana (Gemini) or ChatGPT. Daylight scenes are forgiving, so most attempts land — if the roses overpower the frame, ask for the background slightly more out of focus.', tags='["ai photo prompt", "gemini prompt", "portrait prompt", "men portrait prompt", "outdoor prompt"]' WHERE slug='garden-staircase-portrait-prompt';
-- ===== black blazer over white shirt, warm genuine smile, studio =====
UPDATE prompts SET title='Black Blazer Studio Portrait – Gemini AI Photo Prompt', description='Clean Gemini AI photo prompt for men — a professional studio portrait in an open black blazer and white shirt, warm genuine smile, soft key light. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one sharp front-facing photo, then copy-paste this studio portrait prompt into Nano Banana (Gemini) or ChatGPT. This one works well for profile pictures — keep your natural smile in the source photo and the result stays believable.', tags='["ai photo prompt", "gemini prompt", "portrait prompt", "men portrait prompt", "studio prompt"]' WHERE slug='black-blazer-studio-portrait-prompt';
-- ===== laughing on wooden floor, giant B&W duotone portrait of herself on the wall behind =====
UPDATE prompts SET title='Duotone Wall Portrait – Gemini AI Photo Prompt', description='Creative Gemini AI photo prompt for women — laughing on a wooden floor while a giant black-and-white duotone of the same pose fills the wall behind. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear photo, then copy-paste this creative portrait prompt into Nano Banana (Gemini) or ChatGPT. The wall duotone must repeat your exact pose and laugh — if it drifts into a different expression, re-run and ask for the same pose mirrored.', tags='["ai photo prompt", "gemini prompt", "portrait prompt", "women portrait prompt", "creative prompt"]' WHERE slug='duotone-wall-portrait-prompt';
-- ===== golden-hour seaside cliff, hand on chest, warm smiles =====
UPDATE prompts SET title='Seaside Cliff Couple – Gemini AI Photo Prompt', description='Golden-hour Gemini AI couple photo prompt — standing close on a rocky seaside cliff at sunset, her hand on his chest, both smiling mid-laugh. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one couple photo where both faces are clear, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. Sunset scenes tint skin fast — if faces go orange, ask for natural skin tones and keep the golden light on the sea instead.', tags='["ai photo prompt", "gemini prompt", "couple prompt", "golden hour prompt", "travel prompt"]' WHERE slug='couple-prompt-seaside-cliff';
-- ===== black three-piece suit, luxury sedan, parking garage, bouquet near hip =====
UPDATE prompts SET title='Black Suit Bouquet Portrait – Gemini AI Photo Prompt', description='Sharp Gemini AI photo prompt for men — leaning on a black sedan in a three-piece suit, phone in hand and a bouquet at his hip, garage lighting. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear photo, then copy-paste this men portrait prompt into Nano Banana (Gemini) or ChatGPT. Keep the pose casual against the car — if the suit loses its all-black look under the orange pillars, ask for cooler light on the fabric.', tags='["ai photo prompt", "gemini prompt", "portrait prompt", "men portrait prompt", "cinematic prompt"]' WHERE slug='black-suit-bouquet-portrait-prompt';
-- ===== forehead-to-forehead close-up blending into a golden-hour beach scene =====
UPDATE prompts SET title='Double Exposure Beach Couple – Gemini AI Photo Prompt', description='Artistic Gemini AI couple photo prompt — a forehead-to-forehead close-up that fades, double-exposure style, into the same couple on a golden-hour beach. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo, then copy-paste this double exposure prompt into Nano Banana (Gemini) or ChatGPT. The blend zone is the hard part — if the two halves merge into noise, ask for a cleaner misty transition between the faces and the beach.', tags='["ai photo prompt", "gemini prompt", "couple prompt", "double exposure prompt", "creative prompt"]' WHERE slug='couple-prompt-double-exposure-beach';
-- ===== tags backfill (2026-06-24 batch) =====
UPDATE prompts SET tags='["ai photo prompt", "chatgpt prompt", "lego prompt", "viral prompt", "3d style prompt"]' WHERE slug='lego-viral-prompt';
UPDATE prompts SET tags='["ai photo prompt", "chatgpt prompt", "pixel art prompt", "style prompt", "retro prompt"]' WHERE slug='pixel-style-prompt';
UPDATE prompts SET tags='["ai photo prompt", "chatgpt prompt", "minecraft prompt", "gaming prompt", "3d style prompt"]' WHERE slug='minecraft-prompt';
UPDATE prompts SET tags='["ai photo prompt", "gemini prompt", "motion blur prompt", "cinematic prompt", "street style prompt"]' WHERE slug='motion-blur-prompt';
UPDATE prompts SET tags='["ai photo prompt", "chatgpt prompt", "glassmorphism prompt", "style prompt", "aesthetic prompt"]' WHERE slug='glassmorphism-prompt';
UPDATE prompts SET tags='["ai photo prompt", "gemini prompt", "portrait prompt", "black and white prompt", "studio prompt"]' WHERE slug='black-and-white-studio-prompt';
UPDATE prompts SET tags='["ai photo prompt", "gemini prompt", "dark aesthetic prompt", "aesthetic prompt", "moody prompt"]' WHERE slug='dark-aesthetic-prompt';
UPDATE prompts SET tags='["ai photo prompt", "chatgpt prompt", "gta prompt", "gaming prompt", "viral prompt"]' WHERE slug='gta-vi-prompt';
