-- Description rewrite v2 (2026-06-24): make every description structurally unique
-- (varied opening / verbs / CTA — no shared boilerplate tail) while keeping keyword
-- targeting from seo/keyword-research.md. description is meta-only (not rendered).
-- Supersedes the descriptions in optimize-prompts-2026-06-24.sql.
-- Apply: wrangler d1 execute freepromptbase-com --remote --command "$(grep '^UPDATE' seo/optimize-descriptions-v2-2026-06-24.sql)"

UPDATE prompts SET description='Turn your photo into a man in a white linen shirt holding flowers on a dusk beach. A free Gemini AI photo prompt — copy, paste, and edit in Nano Banana.' WHERE slug='blue-hour-portrait-prompt';
UPDATE prompts SET description='Black-and-white street portrait of a man in a wool overcoat among pigeons in a city square. Paste your photo into this Gemini AI photo prompt and run it in Nano Banana.' WHERE slug='european-city-portrait-prompt';
UPDATE prompts SET description='Make a cinematic World Cup poster — two players back-to-back, neon flags, smoky stadium haze. A copy-paste Gemini AI photo prompt for Nano Banana and ChatGPT.' WHERE slug='cinematic-football-world-cup-poster';
UPDATE prompts SET description='A romantic couple inside a golden glowing circle with neon text and floating hearts. Free Gemini couple photo prompt — add your photo and edit in Nano Banana.' WHERE slug='valentines-day-couple-prompt';
UPDATE prompts SET description='Style a dad and baby in matching suits and sunglasses for a studio shot. Copy this Gemini AI photo prompt, paste your photo, and create it in Nano Banana or ChatGPT.' WHERE slug='father-son-portrait-prompt';
UPDATE prompts SET description='Get the viral night-flash look: a glowing rim-light halo, lens flare, and grainy candid mood. A free Gemini AI photo prompt to copy, paste, and run in Nano Banana.' WHERE slug='back-flash-night-portrait';
UPDATE prompts SET description='Dramatic high-contrast studio portrait of a bearded man in a tailored suit. Copy-paste this Gemini AI photo prompt into Nano Banana — no editing skills required.' WHERE slug='black-and-white-suit-portrait';
UPDATE prompts SET description='A couple holding red roses on a beach, finished with elegant name typography. Free Gemini couple photo prompt — paste your photo and edit in Nano Banana or ChatGPT.' WHERE slug='beach-couple-portrait-prompt';
UPDATE prompts SET description='Stand in tall green grass in a white linen shirt for a moody outdoor portrait. A copy-paste Gemini AI photo prompt — drop in your photo and run it in Nano Banana.' WHERE slug='green-field-portrait-prompt';
UPDATE prompts SET description='Float above a field of flowers, shot worm''s-eye through a floral tunnel. A surreal Gemini AI photo prompt for Nano Banana, ChatGPT, and Midjourney — copy and paste.' WHERE slug='fisheye-floating-photo-prompt';
UPDATE prompts SET description='Become a movie-poster hero in a brown blazer and sunglasses against a blazing sunset. Paste your photo into this Gemini AI photo prompt and generate it in Nano Banana.' WHERE slug='movie-poster-portrait-prompt';
UPDATE prompts SET description='A moody monochrome shot of a stylish man sitting with a horse. This copy-paste Gemini AI photo editing prompt runs in Nano Banana or ChatGPT — just add your photo.' WHERE slug='black-and-white-horse-portrait';
UPDATE prompts SET description='Clean professional headshot of a man in a black tee and glasses on a black backdrop. Copy, paste your photo into this Gemini AI photo prompt, and edit in Nano Banana.' WHERE slug='black-and-white-headshot-prompt';
UPDATE prompts SET description='Create a stylish mirror-selfie portrait in one tap. A free Gemini AI photo prompt (copy paste) — run your photo through Nano Banana or ChatGPT, no signup needed.' WHERE slug='mirror-portrait-prompt';
UPDATE prompts SET description='A dreamy young man in a flower meadow under soft afternoon light. Copy this aesthetic Gemini AI photo prompt and recreate it in Nano Banana, ChatGPT, or Midjourney.' WHERE slug='aesthetic-portrait-prompt';
UPDATE prompts SET description='A stylish young man holding a camera in a cinematic city scene. Paste your photo into this Gemini AI photo prompt and edit it in Nano Banana — copy, paste, done.' WHERE slug='photographer-portrait-prompt';
UPDATE prompts SET description='A romantic outdoor portrait of a couple in a red saree and red shirt. Free Gemini couple photo prompt — copy it, add your photo, and create in Nano Banana.' WHERE slug='indian-couple-portrait-prompt';
UPDATE prompts SET description='A vintage gentleman in a plaid three-piece suit with a walking stick on a cobblestone street. A prompt for Gemini AI you can copy, paste, and run in Nano Banana.' WHERE slug='vintage-gentleman-portrait-prompt';
UPDATE prompts SET description='A stylish man by a vintage street lamp in an autumn park of falling leaves. Copy-paste this Gemini AI photo prompt and bring it to life in Nano Banana or ChatGPT.' WHERE slug='autumn-fashion-portrait-prompt';
UPDATE prompts SET description='A cinematic close-up lit with warm golden and cool green gels on black. Drop your photo into this Gemini AI photo prompt and run it in Nano Banana for instant color.' WHERE slug='color-gel-portrait-prompt';
UPDATE prompts SET description='A bold turquoise fashion portrait that pops. Free Gemini AI photo prompt (copy paste) — paste your photo, edit in Nano Banana or ChatGPT, and create in seconds.' WHERE slug='turquoise-fashion-portrait-prompt';
UPDATE prompts SET description='Suit up as a footballer in a white kit with a ball under bright stadium lights. Copy, paste your photo into this Gemini AI photo prompt, and generate it in Nano Banana.' WHERE slug='footballer-portrait-prompt';
UPDATE prompts SET description='A man in all-black beside a black horse in a snowy forest, fully cinematic. This copy-paste Gemini AI photo editing prompt runs in Nano Banana — just add your photo.' WHERE slug='winter-horse-portrait-prompt';
UPDATE prompts SET description='A melancholic black-and-white man in a coat holding white flowers in the rain. Paste your photo into this Gemini AI photo prompt and edit it in Nano Banana or ChatGPT.' WHERE slug='man-with-flowers-portrait-prompt';
UPDATE prompts SET description='Lean against a matte-black classic bike in warm daylight for a lifestyle shot. A prompt for Gemini AI — copy, paste your photo, and create it in Nano Banana.' WHERE slug='bike-lifestyle-portrait-prompt';
UPDATE prompts SET description='A moody studio portrait wrapped in drifting smoke. Free Gemini AI photo prompt (copy paste) — paste your photo and edit in Nano Banana or ChatGPT in seconds.' WHERE slug='smoky-studio-portrait-prompt';
UPDATE prompts SET description='A woman in a black coat striding through a motion-blurred city street. Copy-paste this Gemini AI photo prompt, add your photo, and run it in Nano Banana.' WHERE slug='urban-motion-portrait-prompt';
UPDATE prompts SET description='Film-noir mood: a black-and-white man on a bokeh-lit street at night. This Gemini AI photo editing prompt is copy-paste — drop in your photo and edit in Nano Banana.' WHERE slug='film-noir-portrait-prompt';
UPDATE prompts SET description='A dramatic close-up sliced by a diagonal light beam and deep shadows. Paste your photo into this Gemini AI photo prompt and run it in Nano Banana for the full effect.' WHERE slug='light-beam-portrait-prompt';
UPDATE prompts SET description='A dramatic black-and-white man in a black mock-neck sweater. Free Gemini AI photo prompt — copy it, paste your photo, and create the look in Nano Banana or ChatGPT.' WHERE slug='monochrome-male-portrait-prompt';
UPDATE prompts SET description='A striking neon-lit portrait of an older man. Free Gemini AI photo prompt (copy paste) — paste your photo and run it through Nano Banana or ChatGPT, then just go.' WHERE slug='old-man-neon-portrait-prompt';
UPDATE prompts SET description='An elegant portrait in a flowing yellow saree. Copy this free Gemini AI photo prompt, paste your photo, and edit it in Nano Banana or ChatGPT — no signup.' WHERE slug='yellow-saree-portrait-prompt';
UPDATE prompts SET description='A black-and-white male portrait with one glowing amber eye and wet skin droplets. Copy-paste this Gemini AI photo editing prompt and run it in Nano Banana.' WHERE slug='selective-color-portrait-prompt';
UPDATE prompts SET description='A dramatic chiaroscuro portrait carved from light and shadow. Free Gemini AI photo prompt (copy paste) — paste your photo and recreate it in Nano Banana or ChatGPT.' WHERE slug='chiaroscuro-portrait-prompt';
UPDATE prompts SET description='A stylish portrait in a bold floral shirt. A prompt for Gemini AI you can copy and paste — add your photo and create the look in Nano Banana or ChatGPT.' WHERE slug='floral-shirt-portrait-prompt';
UPDATE prompts SET description='A candid portrait caught mid-stride on a busy city crosswalk. Copy this Gemini AI photo prompt, paste your photo, and edit it in Nano Banana or ChatGPT.' WHERE slug='city-crosswalk-portrait-prompt';
UPDATE prompts SET description='A woman in a black coat glancing back in a sunlit gothic hall, fully cinematic. Paste your photo into this Gemini AI photo prompt and run it in Nano Banana.' WHERE slug='gothic-hall-portrait-prompt';
UPDATE prompts SET description='A cinematic portrait set in falling snow at night. Copy this free Gemini AI photo prompt, paste your photo, and edit it in Nano Banana or ChatGPT.' WHERE slug='snowy-night-portrait-prompt';
UPDATE prompts SET description='Add playful doodles, motion lines, and captions that react to your subject. A free Gemini AI photo prompt — copy, paste your photo, and run it in Nano Banana or ChatGPT.' WHERE slug='hand-drawn-doodle-overlay';
UPDATE prompts SET description='Turn one photo into a Pixar chibi scrapbook collage — 3D chibi poses with doodles and stickers. A copy-paste Gemini AI photo prompt for Nano Banana and ChatGPT.' WHERE slug='pixar-chibi-scrapbook-collage';
UPDATE prompts SET description='Design sleek glassmorphism visuals — translucent panels, frosted textures, gradients, soft shadows. A free AI prompt you can copy and paste into ChatGPT or Gemini.' WHERE slug='glassmorphism-prompt';
UPDATE prompts SET description='Build viral LEGO-style art — realistic minifigs, characters, and cinematic block scenes. Copy this free AI prompt and paste it into ChatGPT or Gemini to create.' WHERE slug='lego-viral-prompt';
UPDATE prompts SET description='Generate block-style Minecraft art — characters, epic castles, and cinematic scenes. A free AI prompt; copy it, paste into ChatGPT or Gemini, and build.' WHERE slug='minecraft-prompt';
UPDATE prompts SET description='A striking black-and-white studio portrait with deep shadows and high contrast. A free AI photo prompt — paste your photo into Gemini (Nano Banana) or ChatGPT.' WHERE slug='black-and-white-studio-prompt';
UPDATE prompts SET description='Make retro pixel art — 8-bit characters, gaming scenes, and pixel avatars. Copy this free AI prompt and paste it into ChatGPT or Gemini to generate.' WHERE slug='pixel-style-prompt';
UPDATE prompts SET description='Freeze the action with cinematic motion blur, speed trails, and real movement. A free AI photo prompt — copy, paste it into ChatGPT or Gemini and generate.' WHERE slug='motion-blur-prompt';
UPDATE prompts SET description='Striking dark-aesthetic portraits with low-key lighting and cinematic shadows. A free AI photo prompt — paste your photo into Gemini or ChatGPT and set the mood.' WHERE slug='dark-aesthetic-prompt';
UPDATE prompts SET description='Drop into a GTA VI world — neon streets, dramatic sunsets, stylish characters. A free GTA 6 style AI prompt; copy, paste into ChatGPT or Gemini, and generate.' WHERE slug='gta-vi-prompt';
