-- SEO optimization of prompt titles + meta descriptions (2026-06-24)
-- Targets keywords from seo/keyword-research.md:
--   * "gemini ai photo prompt" / "...copy paste"  (Cluster B, KD 26 — best low-comp target)
--   * "nano banana" / "nano banana prompt"          (Cluster A — 110K breakout; the Gemini image model)
--   * per-prompt style keyword + "couple"           (Cluster D)
-- Only `title` and `description` change. slug / prompt_text / H1 (slug-derived) untouched.
-- Description is meta-only (never rendered visibly). Backup: prompts-title-desc-backup-2026-06-24.json
-- Apply: wrangler d1 execute freepromptbase-com --remote --file=seo/optimize-prompts-2026-06-24.sql

-- ===== Group A: Gemini photo-portrait prompts =====
UPDATE prompts SET title='Blue Hour Beach Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt — turn your photo into a man in a white linen shirt with white flowers on a beach at dusk. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='blue-hour-portrait-prompt';
UPDATE prompts SET title='European City Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt (copy paste): turn your pic into a B&W man in a wool overcoat among pigeons in a city square. Edit in Nano Banana / Gemini.' WHERE slug='european-city-portrait-prompt';
UPDATE prompts SET title='World Cup Football Poster – Gemini AI Photo Prompt', description='Gemini AI photo prompt for a cinematic World Cup poster — two players back-to-back, neon flags, smoky stadium haze. Copy, paste in Gemini (Nano Banana) & ChatGPT.' WHERE slug='cinematic-football-world-cup-poster';
UPDATE prompts SET title='Valentine''s Day Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — turn your photo into a romantic couple in a golden glowing circle with neon text and floating hearts. Copy, paste in Nano Banana.' WHERE slug='valentines-day-couple-prompt';
UPDATE prompts SET title='Father & Son Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: turn your photo into a stylish man and baby in matching suits and sunglasses in a studio. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='father-son-portrait-prompt';
UPDATE prompts SET title='Back-Flash Night Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt — a night iPhone-flash look with a glowing rim-light halo, lens flare and grainy candid mood. Copy, paste your photo in Nano Banana (Gemini).' WHERE slug='back-flash-night-portrait';
UPDATE prompts SET title='B&W Suit Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt (copy paste): turn your pic into a dramatic high-contrast studio shot of a bearded man in a tailored suit. Edit in Nano Banana / Gemini.' WHERE slug='black-and-white-suit-portrait';
UPDATE prompts SET title='Beach Couple Portrait – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — turn your photo into a couple holding red roses on a beach with elegant name typography. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='beach-couple-portrait-prompt';
UPDATE prompts SET title='Green Field Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: turn your photo into a moody portrait in a white linen shirt in tall green grass. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='green-field-portrait-prompt';
UPDATE prompts SET title='Fisheye Floating Photo – Gemini AI Photo Prompt', description='Gemini AI photo prompt — a person levitating above a field of flowers, shot worm''s-eye through a floral tunnel. Copy, paste in Nano Banana (Gemini) & Midjourney.' WHERE slug='fisheye-floating-photo-prompt';
UPDATE prompts SET title='Movie Poster Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt (copy paste): turn your pic into a heroic male lead in a brown blazer and sunglasses against a sunset sky. Edit in Nano Banana / Gemini.' WHERE slug='movie-poster-portrait-prompt';
UPDATE prompts SET title='B&W Horse Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: turn your photo into a moody monochrome shot of a stylish man sitting with a horse. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='black-and-white-horse-portrait';
UPDATE prompts SET title='B&W Pro Headshot – Gemini AI Photo Prompt', description='Gemini AI photo prompt — turn your photo into a clean professional headshot of a man in a black tee and glasses on a black backdrop. Copy, paste in Nano Banana (Gemini).' WHERE slug='black-and-white-headshot-prompt';
UPDATE prompts SET title='Mirror Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt (copy paste): create a stylish mirror selfie portrait. Paste your photo and edit in Nano Banana (Gemini) & ChatGPT — no signup.' WHERE slug='mirror-portrait-prompt';
UPDATE prompts SET title='Aesthetic Meadow Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt — a dreamy young man in a flower meadow in soft afternoon light. Copy, paste your photo in Nano Banana (Gemini), ChatGPT or Midjourney.' WHERE slug='aesthetic-portrait-prompt';
UPDATE prompts SET title='Photographer Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt (copy paste): turn your pic into a stylish young man holding a camera in a cinematic urban setting. Edit in Nano Banana / Gemini & ChatGPT.' WHERE slug='photographer-portrait-prompt';
UPDATE prompts SET title='Indian Couple Portrait – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — turn your photo into a romantic couple in a red saree and red shirt. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='indian-couple-portrait-prompt';
UPDATE prompts SET title='Vintage Gentleman Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: a man in a plaid three-piece suit with a walking stick on a cobblestone street. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='vintage-gentleman-portrait-prompt';
UPDATE prompts SET title='Autumn Fashion Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt — a stylish man by a vintage street lamp in an autumn park with falling leaves. Copy, paste your photo in Nano Banana (Gemini) & ChatGPT.' WHERE slug='autumn-fashion-portrait-prompt';
UPDATE prompts SET title='Color Gel Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt (copy paste): a cinematic close-up lit with warm golden and cool green gels on black. Edit in Nano Banana / Gemini & ChatGPT.' WHERE slug='color-gel-portrait-prompt';
UPDATE prompts SET title='Turquoise Fashion Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt (copy paste): a bold turquoise fashion portrait. Paste your photo and edit in Nano Banana (Gemini) & ChatGPT — create in seconds.' WHERE slug='turquoise-fashion-portrait-prompt';
UPDATE prompts SET title='Footballer Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt — turn your photo into a footballer in a white kit with a ball under bright stadium lights. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='footballer-portrait-prompt';
UPDATE prompts SET title='Winter Horse Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt — a man in all-black with a black horse in a snowy forest, cinematic. Copy, paste your photo in Nano Banana (Gemini) & ChatGPT.' WHERE slug='winter-horse-portrait-prompt';
UPDATE prompts SET title='Man With Flowers Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt (copy paste): a melancholic B&W man in a coat holding white flowers in the rain. Edit in Nano Banana / Gemini & ChatGPT.' WHERE slug='man-with-flowers-portrait-prompt';
UPDATE prompts SET title='Bike Lifestyle Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: a stylish man leaning on a matte black classic bike in warm daylight. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='bike-lifestyle-portrait-prompt';
UPDATE prompts SET title='Smoky Studio Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt (copy paste): a moody smoky studio portrait. Paste your photo and edit in Nano Banana (Gemini) & ChatGPT — create in seconds.' WHERE slug='smoky-studio-portrait-prompt';
UPDATE prompts SET title='Urban Motion Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt — a woman in a black coat walking through a motion-blurred city street. Copy, paste your photo in Nano Banana (Gemini) & ChatGPT.' WHERE slug='urban-motion-portrait-prompt';
UPDATE prompts SET title='Film Noir Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt (copy paste): a B&W man on a bokeh-lit city street at night. Edit in Nano Banana / Gemini & ChatGPT.' WHERE slug='film-noir-portrait-prompt';
UPDATE prompts SET title='Light Beam Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt — a dramatic close-up with a diagonal light beam across the face and deep shadows. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='light-beam-portrait-prompt';
UPDATE prompts SET title='Monochrome Male Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: a dramatic B&W man in a black mock-neck sweater. Copy, paste your photo in Nano Banana (Gemini) & ChatGPT.' WHERE slug='monochrome-male-portrait-prompt';
UPDATE prompts SET title='Old Man Neon Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt (copy paste): a striking old-man neon portrait. Paste your photo and edit in Nano Banana (Gemini) or ChatGPT — just copy and go.' WHERE slug='old-man-neon-portrait-prompt';
UPDATE prompts SET title='Yellow Saree Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: an elegant yellow saree portrait. Copy it, paste your photo, and edit in Nano Banana (Gemini) & ChatGPT — no signup.' WHERE slug='yellow-saree-portrait-prompt';
UPDATE prompts SET title='Selective Color Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt (copy paste): a B&W male portrait with a glowing amber eye and wet skin droplets. Edit in Nano Banana / Gemini & ChatGPT.' WHERE slug='selective-color-portrait-prompt';
UPDATE prompts SET title='Chiaroscuro Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt (copy paste): a dramatic chiaroscuro portrait. Paste your photo and recreate the look in Nano Banana (Gemini) or ChatGPT.' WHERE slug='chiaroscuro-portrait-prompt';
UPDATE prompts SET title='Floral Shirt Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: a stylish floral-shirt portrait. Copy, paste your photo and create it in Nano Banana (Gemini) or ChatGPT — just go.' WHERE slug='floral-shirt-portrait-prompt';
UPDATE prompts SET title='City Crosswalk Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: a candid city-crosswalk portrait. Copy it, paste your photo, and edit in Nano Banana (Gemini) & ChatGPT.' WHERE slug='city-crosswalk-portrait-prompt';
UPDATE prompts SET title='Gothic Hall Portrait – Gemini AI Photo Prompt', description='Gemini AI photo prompt — a woman in a black coat glancing back in a sunlit gothic hall, cinematic. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='gothic-hall-portrait-prompt';
UPDATE prompts SET title='Snowy Night Portrait – Gemini AI Photo Prompt', description='Free Gemini AI photo prompt: a cinematic snowy-night portrait. Copy it, paste your photo, and edit in Nano Banana (Gemini) & ChatGPT.' WHERE slug='snowy-night-portrait-prompt';

UPDATE prompts SET title='Hand-Drawn Doodle Overlay – Gemini AI Photo Prompt', description='Gemini AI photo prompt — add playful doodles, motion lines and captions that react to your subject in any photo. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='hand-drawn-doodle-overlay';
UPDATE prompts SET title='Pixar Chibi Scrapbook Collage – Gemini AI Photo Prompt', description='Gemini AI photo prompt — turn your photo into a Pixar chibi scrapbook collage: 3D chibi poses with doodles and sticker outlines. Copy, paste in Nano Banana (Gemini) & ChatGPT.' WHERE slug='pixar-chibi-scrapbook-collage';

-- ===== Group B: ChatGPT / style generation prompts (own style keyword) =====
UPDATE prompts SET title='Glassmorphism Prompt – Free AI Design Prompt', description='Free Glassmorphism AI prompt — create elegant designs with translucent glass panels, frosted textures, gradients and soft shadows. Copy, paste into ChatGPT or Gemini.' WHERE slug='glassmorphism-prompt';
UPDATE prompts SET title='Lego Prompt – Viral LEGO AI Prompt', description='Free viral LEGO AI prompt — generate realistic LEGO characters, mini-figures and cinematic block scenes. Copy, paste into ChatGPT or Gemini and create.' WHERE slug='lego-viral-prompt';
UPDATE prompts SET title='Minecraft Prompt – Viral Minecraft AI Prompt', description='Free Minecraft AI prompt — generate block-style characters, epic castles and cinematic Minecraft scenes. Copy, paste into ChatGPT or Gemini and create.' WHERE slug='minecraft-prompt';
UPDATE prompts SET title='B&W Studio Portrait – AI Photo Prompt', description='Free AI photo prompt for a striking B&W studio portrait — studio lighting, deep shadows, high contrast. Copy, paste your photo into Gemini (Nano Banana) or ChatGPT.' WHERE slug='black-and-white-studio-prompt';
UPDATE prompts SET title='Pixel Style Prompt – Free Pixel Art AI Prompt', description='Free pixel-art AI prompt — generate 8-bit characters, retro gaming scenes and pixel avatars. Copy, paste into ChatGPT or Gemini and create viral pixel art.' WHERE slug='pixel-style-prompt';
UPDATE prompts SET title='Motion Blur Prompt – Viral AI Photo Prompt', description='Free motion blur AI prompt — create cinematic action shots with dynamic speed trails and realistic movement. Copy, paste into ChatGPT or Gemini.' WHERE slug='motion-blur-prompt';
UPDATE prompts SET title='Dark Aesthetic Prompt – AI Portrait Prompt', description='Free dark aesthetic AI prompt — striking portraits with low-key lighting, cinematic shadows and intense mood. Copy, paste your photo into Gemini or ChatGPT.' WHERE slug='dark-aesthetic-prompt';
UPDATE prompts SET title='GTA VI Prompt – GTA 6 Style AI Prompt', description='Free GTA VI style AI prompt — generate cinematic open-world scenes with neon streets, sunsets and stylish characters. Copy, paste into ChatGPT or Gemini.' WHERE slug='gta-vi-prompt';
