-- Fill empty how_to_use sections with genuinely useful guidance + secondary/long-tail
-- keywords (2026-06-24). how_to_use IS rendered visibly (the "How to use it" card), so
-- this is real body content, not meta. Only the 43 EMPTY rows are touched; the 5 already
-- filled (hand-drawn-doodle-overlay, cinematic-football-world-cup-poster, back-flash-night-
-- portrait, glassmorphism-prompt, pixar-chibi-scrapbook-collage) are left as-is.
-- Long-tail targets: gemini ai photo prompt copy paste, prompt for gemini ai,
-- gemini couple photo prompt, gemini ai photo editing prompt, nano banana / nano banana ai.
-- Backup: prompts-howto-backup-2026-06-24.json
-- Apply: wrangler d1 execute freepromptbase-com --remote --command "$(grep '^UPDATE' seo/optimize-howto-2026-06-24.sql)"

-- ===== Gemini photo-portrait prompts =====
UPDATE prompts SET how_to_use='Copy the prompt, upload a clear front-facing photo, and run it as a gemini ai photo prompt (copy paste) in Gemini''s Nano Banana or ChatGPT. Keep a 4:5 or 9:16 vertical frame for the dusk beach look, and re-run once if the face drifts.' WHERE slug='blue-hour-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste your photo and the prompt into Gemini (Nano Banana) or ChatGPT. For this black-and-white street look, use a clear half-body shot so the overcoat and pigeons compose well. This prompt for gemini ai works best in a 4:5 vertical frame.' WHERE slug='european-city-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload one clear couple photo, then copy-paste this gemini couple photo prompt into Nano Banana (Gemini) or ChatGPT. Keep both faces visible and well-lit; a 4:5 vertical frame suits the glowing circle and floating hearts.' WHERE slug='valentines-day-couple-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Use a clear photo where both faces show, then run this gemini ai photo prompt in Nano Banana (Gemini) or ChatGPT. If the baby''s features drift, re-run with the same prompt — the model usually locks in on the second try.' WHERE slug='father-son-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy, paste your photo, and generate in Gemini (Nano Banana) or ChatGPT. A sharp, well-lit headshot gives the cleanest high-contrast suit portrait. This is a copy-paste gemini ai photo prompt — no editing skills needed.' WHERE slug='black-and-white-suit-portrait' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste one clear couple photo and this gemini couple photo prompt into Nano Banana (Gemini) or ChatGPT. Replace the name typography with your own, and keep a 4:5 vertical frame for the beach composition.' WHERE slug='beach-couple-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload a clear photo and copy-paste the prompt into Gemini (Nano Banana) or ChatGPT. For this aesthetic gemini ai photo prompt, a waist-up shot in soft daylight matches the green-field mood best.' WHERE slug='green-field-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='This works as a gemini ai photo prompt or in Midjourney. Upload a full-body photo so the levitation pose reads clearly, and keep a vertical frame. Re-run if the floral tunnel looks flat.' WHERE slug='fisheye-floating-photo-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy-paste your photo and the prompt into Nano Banana (Gemini) or ChatGPT. A confident half-body shot gives the best movie-poster look; 9:16 vertical sells the cinematic framing. A solid prompt for gemini ai poster edits.' WHERE slug='movie-poster-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste a clear photo into Gemini (Nano Banana) or ChatGPT with this prompt. Half-body framing works best so both the man and horse fit. This gemini ai photo editing prompt is copy-paste — no manual retouching.' WHERE slug='black-and-white-horse-portrait' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload a clean front-facing photo, then copy-paste this gemini ai photo prompt into Nano Banana (Gemini) or ChatGPT. Good lighting on the face gives the sharpest professional headshot. Re-run once if needed.' WHERE slug='black-and-white-headshot-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy the prompt, upload a clear selfie or portrait, and run it in Gemini (Nano Banana) or ChatGPT. This is a free gemini ai photo prompt (copy paste) — keep a vertical 4:5 frame for the mirror look.' WHERE slug='mirror-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Works as a gemini ai photo prompt, in ChatGPT, or in Midjourney. Upload a waist-up photo in soft light and paste the prompt. Keep the frame vertical so the flower meadow fills the background.' WHERE slug='aesthetic-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste your photo and the prompt into Nano Banana (Gemini) or ChatGPT. A half-body shot holding anything camera-like helps the pose; 4:5 vertical suits the urban setting. A clean copy-paste gemini ai photo prompt.' WHERE slug='photographer-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload one clear couple photo and copy-paste this gemini couple photo prompt into Nano Banana (Gemini) or ChatGPT. Keep both faces lit and use a vertical frame for the outdoor portrait.' WHERE slug='indian-couple-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy-paste your photo into Gemini (Nano Banana) or ChatGPT with the prompt. A standing full or half-body shot lets the suit and walking stick show. This prompt for gemini ai keeps faces accurate on a re-run.' WHERE slug='vintage-gentleman-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste a clear photo and the prompt into Nano Banana (Gemini) or ChatGPT. Waist-up framing in warm light matches the autumn-park mood. A simple gemini ai photo prompt copy paste — no edits needed.' WHERE slug='autumn-fashion-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload a sharp close-up and copy-paste this gemini ai photo prompt into Nano Banana (Gemini) or ChatGPT. A tight head-and-shoulders crop lets the warm and cool gels read; re-run for stronger color.' WHERE slug='color-gel-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy the prompt, paste your photo, and run it in Gemini (Nano Banana) or ChatGPT. This free gemini ai photo prompt works best on a clear portrait in 4:5 vertical for the bold turquoise styling.' WHERE slug='turquoise-fashion-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste a clear photo and the prompt into Nano Banana (Gemini) or ChatGPT. A standing full-body shot suits the kit-and-ball pose; 9:16 vertical sells the stadium backdrop. A copy-paste gemini ai photo prompt.' WHERE slug='footballer-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy-paste your photo into Gemini (Nano Banana) or ChatGPT with the prompt. Half- or full-body framing fits both subject and horse. This gemini ai photo editing prompt locks faces on a second run if needed.' WHERE slug='winter-horse-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload a clear photo and paste the prompt into Nano Banana (Gemini) or ChatGPT. A half-body shot in even light gives the cleanest moody black-and-white result. A ready copy-paste gemini ai photo prompt.' WHERE slug='man-with-flowers-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste your photo and the prompt into Gemini (Nano Banana) or ChatGPT. A standing or leaning pose matches the bike scene; keep a 4:5 vertical frame. A simple prompt for gemini ai lifestyle edits.' WHERE slug='bike-lifestyle-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy the prompt, upload a clear portrait, and generate in Gemini (Nano Banana) or ChatGPT. This free gemini ai photo prompt (copy paste) suits a head-and-shoulders crop; re-run for more haze.' WHERE slug='smoky-studio-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste a clean, well-lit photo into Gemini (Nano Banana) or ChatGPT with the prompt. A front-facing headshot gives the strongest high-contrast monochrome. Works as a copy-paste ai photo prompt — no editing needed.' WHERE slug='black-and-white-studio-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload a clear photo and copy-paste this gemini ai photo prompt into Nano Banana (Gemini) or ChatGPT. A standing half-body shot keeps the subject sharp against the motion-blurred street; use a vertical frame.' WHERE slug='urban-motion-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy-paste your photo into Gemini (Nano Banana) or ChatGPT. A half-body night shot reads best for the noir look. This gemini ai photo editing prompt keeps the face accurate on a re-run.' WHERE slug='film-noir-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste a sharp close-up and the prompt into Nano Banana (Gemini) or ChatGPT. A tight face crop lets the diagonal light beam land. A copy-paste gemini ai photo prompt — re-run for deeper shadows.' WHERE slug='light-beam-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload a clear front-facing photo and copy-paste this gemini ai photo prompt into Gemini (Nano Banana) or ChatGPT. Even lighting gives the cleanest monochrome; keep a 4:5 vertical frame.' WHERE slug='monochrome-male-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy the prompt, paste your photo, and run it in Nano Banana (Gemini) or ChatGPT. This free gemini ai photo prompt (copy paste) suits a close or half-body portrait; re-run for stronger neon.' WHERE slug='old-man-neon-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste a clear photo and the prompt into Gemini (Nano Banana) or ChatGPT. A waist-up shot frames the saree well; keep a 4:5 vertical. A simple gemini ai photo prompt copy paste — no edits required.' WHERE slug='yellow-saree-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload a sharp close-up and copy-paste this gemini ai photo editing prompt into Nano Banana (Gemini) or ChatGPT. A tight face crop helps the selective amber eye and droplets read; re-run if the color spreads.' WHERE slug='selective-color-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy-paste your photo into Gemini (Nano Banana) or ChatGPT with the prompt. A head-and-shoulders crop in low light suits the dramatic chiaroscuro. A ready copy-paste gemini ai photo prompt.' WHERE slug='chiaroscuro-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste your photo and the prompt into Nano Banana (Gemini) or ChatGPT. A half-body shot shows the floral shirt best; keep a vertical frame. A simple prompt for gemini ai fashion edits.' WHERE slug='floral-shirt-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Upload a clear photo and copy-paste this gemini ai photo prompt into Gemini (Nano Banana) or ChatGPT. A standing half- or full-body shot fits the crosswalk scene; use a 4:5 or 9:16 vertical frame.' WHERE slug='city-crosswalk-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy the prompt, paste your photo, and run it in Nano Banana (Gemini) or ChatGPT. This free gemini ai photo prompt suits a half-body shot; keep vertical framing for the snowy-night mood.' WHERE slug='snowy-night-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste a clear photo and the prompt into Gemini (Nano Banana) or ChatGPT. A standing half-body shot fits the hall composition; 4:5 vertical works best. A copy-paste gemini ai photo editing prompt.' WHERE slug='gothic-hall-portrait-prompt' AND (how_to_use IS NULL OR how_to_use='');

-- ===== ChatGPT / style generation prompts (no photo needed) =====
UPDATE prompts SET how_to_use='No photo needed — copy-paste this LEGO prompt into ChatGPT or Gemini and describe the character or scene you want. Swap in your own subject (a person, pet, or logo) to make a viral LEGO-style ai image. Re-run for different minifig poses.' WHERE slug='lego-viral-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy-paste this Minecraft prompt into ChatGPT or Gemini, then name the character, mob, or build you want. No photo required — describe the scene and re-run for block-style variations. A free Minecraft ai prompt anyone can use.' WHERE slug='minecraft-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste this pixel style prompt into ChatGPT or Gemini and add your subject — a character, avatar, or scene. No upload needed; lower the detail for true 8-bit retro art. Re-run to get different pixel-art variations.' WHERE slug='pixel-style-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy-paste this motion blur prompt into ChatGPT or Gemini and describe the action or subject. Add a direction of movement for stronger speed trails. Works as a free ai photo prompt — no upload required.' WHERE slug='motion-blur-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Paste this dark aesthetic prompt into Gemini or ChatGPT. You can upload a portrait to restyle it, or just describe a subject for a fresh image. Keep the lighting low-key and re-run for moodier shadows.' WHERE slug='dark-aesthetic-prompt' AND (how_to_use IS NULL OR how_to_use='');
UPDATE prompts SET how_to_use='Copy-paste this GTA VI style prompt into ChatGPT or Gemini and describe your character or scene. Upload a photo to put yourself in the GTA 6 look, or generate from text. Re-run for different neon-lit variations.' WHERE slug='gta-vi-prompt' AND (how_to_use IS NULL OR how_to_use='');
