-- SEO pass for the 6 newly-approved prompts (2026-07-13) — dates 2026-07-13..14, all had
-- EMPTY description/how_to_use and empty tags ('[]').
-- Touches ONLY SEO fields: title, description (meta), how_to_use (rendered body), tags.
-- prompt_text is NEVER modified. Keyword targeting per seo/keyword-research.md +
-- seo/tracklist.md: gemini ai photo prompt (copy paste) / couple prompt / gemini couple photo
-- prompt, Nano Banana, India/SE-Asia. Descriptions are structurally unique (no shared
-- boilerplate). Backup of prior (empty) values: seo/new-prompts-backup-2026-07-13.json.
-- All 6 slugs renamed in rename-descriptive-slugs-2026-07-13.sql (run that FIRST).

-- ===== B&W editorial woman, sheer mesh turtleneck, split black/white backdrop =====
UPDATE prompts SET title='B&W Women Portrait – Gemini AI Photo Prompt', description='Black and white Gemini AI photo prompt — an editorial portrait of a woman in a sheer mesh turtleneck against a split black-and-white backdrop, shot on medium-format film. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear front-facing photo, then copy-paste this black and white portrait prompt into Nano Banana (Gemini) or ChatGPT. The split black/white backdrop needs a vertical frame — re-run once if the high-contrast lighting loses the shadow side of the face.', tags='["ai photo prompt","gemini prompt","portrait prompt","women portrait prompt","editorial prompt"]' WHERE slug='black-and-white-women-portrait-prompt';

-- ===== Indian couple, red silk saree + gold zari, vine-draped stone wall, golden hour =====
UPDATE prompts SET title='Red Saree Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a tender pre-wedding portrait against a vine-draped stone wall, red silk saree with gold zari, jhumkas and warm golden-hour light. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. The pose puts foreheads nearly touching in profile — add "keep both faces recognizable" if the likeness drifts, and keep the vertical frame so the saree drape and hanging vines stay in shot.', tags='["ai photo prompt","gemini prompt","couple prompt","indian aesthetic prompt","wedding prompt"]' WHERE slug='couple-prompt-red-saree';

-- ===== Mid-stride walk through a sunlit classical colonnade, street-style editorial =====
UPDATE prompts SET title='Colonnade Fashion Portrait – Gemini AI Prompt', description='Editorial fashion Gemini AI photo prompt — a confident mid-stride walk through a sunlit stone colonnade, brown camp-collar shirt, cream pleated trousers and long diagonal shadows. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear full-body photo, then copy-paste this fashion portrait prompt into Nano Banana (Gemini) or ChatGPT. Ask for a vertical 4:5 frame so the head-to-shoe walking pose and the columns both fit — re-run once if the hard side light blows out the sunlit stripe on the path.', tags='["ai photo prompt","gemini prompt","fashion prompt","men portrait prompt","editorial prompt"]' WHERE slug='colonnade-fashion-portrait-prompt';

-- ===== Golden-hour blazer portrait, wayfarers, teal-and-amber sunset sky =====
UPDATE prompts SET title='Golden Hour Blazer Portrait – Gemini AI Prompt', description='Cinematic Gemini AI photo prompt — a golden-hour portrait in a brown blazer and black wayfarers, warm rim light and a teal-and-amber sunset sky. Copy, paste your photo in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear photo of your face, then copy-paste this gemini ai photo prompt into Nano Banana (Gemini) or ChatGPT. The look includes sunglasses — add "no sunglasses" if you want your eyes visible, and re-run once if the teal-orange grade shifts your skin tone.', tags='["ai photo prompt","gemini prompt","portrait prompt","men portrait prompt","cinematic prompt"]' WHERE slug='golden-hour-blazer-portrait-prompt';

-- ===== Low-key B&W studio portrait, round wire glasses, fist at the jaw =====
UPDATE prompts SET title='B&W Glasses Portrait – Gemini AI Photo Prompt', description='Low-key black and white portrait prompt — round wire glasses, a fist resting at the jaw and a single soft key light against a pure black studio backdrop. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear front-facing photo, then copy-paste this black and white portrait prompt into Nano Banana (Gemini) or ChatGPT. Deep shadows fall across half the frame — keep the vertical crop from mid-torso up, and re-run once if the low-key light hides too much of the face.', tags='["ai photo prompt","gemini prompt","portrait prompt","men portrait prompt","cinematic prompt"]' WHERE slug='black-and-white-glasses-portrait-prompt';

-- ===== Clifftop travel selfie over a turquoise ocean, matching white linen =====
UPDATE prompts SET title='Cliff Selfie Couple – Gemini AI Photo Prompt', description='Gemini AI couple photo prompt — a wide-angle travel selfie at a Bali-style clifftop viewpoint, turquoise ocean and sea stacks below, matching all-white linen outfits. Copy, paste in Nano Banana (Gemini) & ChatGPT.', how_to_use='Upload one clear couple photo where both faces show, then copy-paste this couple prompt into Nano Banana (Gemini) or ChatGPT. It is a wide-angle selfie, so keep the vertical 3:4 frame with the outstretched arm in shot — both wear sunglasses, so add "no sunglasses" if you want faces fully visible.', tags='["ai photo prompt","gemini prompt","couple prompt","travel prompt","aesthetic prompt"]' WHERE slug='couple-prompt-cliff-selfie';
