// Generates db/seed.sql from the seed data in src/data.
// Run:  node --experimental-strip-types scripts/gen-seed.ts
// (wired up as `npm run db:gen-seed`)

import { prompts } from '../src/data/prompts.ts';
import { categories } from '../src/data/categories.ts';
import { posts } from '../src/data/posts.ts';
import { writeFileSync, mkdirSync } from 'node:fs';

// Escape single quotes, and break each real newline so the resulting SQL is
// a single physical line. wrangler's `d1 execute --file` ingester treats
// newlines as statement boundaries, so a multi-line string literal would be
// truncated and the INSERT would silently no-op. Splice `' || char(10) || '`
// in place of each \n so the runtime reconstructs the original string.
const q = (s: string) => {
	const escaped = s.replace(/'/g, "''");
	const parts = escaped.split('\n');
	if (parts.length === 1) return `'${parts[0]}'`;
	return parts.map((p) => `'${p}'`).join(" || char(10) || ");
};
const nullable = (s?: string) => (s ? q(s) : 'NULL');

const lines: string[] = ['-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.'];

categories.forEach((c, i) => {
	lines.push(
		`INSERT INTO prompt_categories (slug,name,description,emoji,sort_order) VALUES (${q(c.slug)},${q(c.name)},${q(c.description)},${q(c.emoji)},${i});`,
	);
});

for (const p of prompts) {
	lines.push(
		`INSERT INTO prompts (slug,title,description,prompt_text,category,tags,author,date,cover_image,images,featured,liked,popularity,save_count,like_count,share_count,how_to_use) VALUES (` +
			[
				q(p.slug),
				q(p.title),
				q(p.description),
				q(p.promptText),
				q(p.category),
				q(JSON.stringify(p.tags)),
				q(p.author),
				q(p.date),
				nullable(p.coverImage),
				q(JSON.stringify(p.images ?? [])),
				p.featured ? 1 : 0,
				p.liked ? 1 : 0,
				p.popularity,
				p.saveCount ?? p.popularity,
				p.likeCount ?? 0,
				p.shareCount ?? 0,
				nullable(p.howToUse),
			].join(',') +
			`);`,
	);
}

for (const p of posts) {
	lines.push(
		`INSERT INTO posts (id,slug,title,excerpt,content,author_name,status,read_time,cover_image,meta_description,published_at) VALUES (` +
			[
				q(p.id),
				q(p.slug),
				q(p.title),
				q(p.excerpt),
				q(p.content),
				q(p.authorName),
				q('published'),
				q(p.readTime),
				nullable(p.coverImage),
				nullable(p.metaDescription),
				q(p.publishedAt),
			].join(',') +
			`);`,
	);
}

mkdirSync('db', { recursive: true });
writeFileSync('db/seed.sql', lines.join('\n') + '\n');
console.log(
	`Wrote db/seed.sql (${categories.length} categories, ${prompts.length} prompts, ${posts.length} posts)`,
);
